# Generated by Django 4.2.20 on 2025-03-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
