# Generated by Django 4.2.20 on 2025-03-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit_is_completed_habit_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='paragraph',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
