# Generated by Django 4.2.20 on 2025-03-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_paragraph_note_content_remove_note_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='heading',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='kk', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
